name: Build Binary

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

permissions:
   contents: write

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Test
      run: |
        make test

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      id: build
      run: |
        make RELEASE=1 ARCH_POSTFIX=_${{ matrix.arch }} install
        echo "file=$(ls dist/* | head -n 1)" >> "$GITHUB_OUTPUT"
      env:
        GOARCH: ${{ matrix.arch }}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.arch }}
        path: ${{ steps.build.outputs.file }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:

    - name: Download
      uses: actions/download-artifact@v5
      with:
        pattern: binary-*
        path: ./binaries
        merge-multiple: true

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: |
          ./binaries/*